// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ikDZ6Dwn56D5vz6JSyBWL-FGsXazFLQ',
    appId: '1:308069335701:web:12aa2f0f7ec9e5c8add19c',
    messagingSenderId: '308069335701',
    projectId: 'chatapp-376d0',
    authDomain: 'chatapp-376d0.firebaseapp.com',
    storageBucket: 'chatapp-376d0.appspot.com',
    measurementId: 'G-66TY14YLCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbklCdzK1u_WCp9AljWFWarYfCYUXajs',
    appId: '1:308069335701:android:ed00fef3914ed119add19c',
    messagingSenderId: '308069335701',
    projectId: 'chatapp-376d0',
    storageBucket: 'chatapp-376d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-B-p--f_pR1WirHf-Of-BrbPXI25xQOs',
    appId: '1:308069335701:ios:d2f462d331742e55add19c',
    messagingSenderId: '308069335701',
    projectId: 'chatapp-376d0',
    storageBucket: 'chatapp-376d0.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-B-p--f_pR1WirHf-Of-BrbPXI25xQOs',
    appId: '1:308069335701:ios:2c605945aec487a6add19c',
    messagingSenderId: '308069335701',
    projectId: 'chatapp-376d0',
    storageBucket: 'chatapp-376d0.appspot.com',
    iosBundleId: 'com.example.dashboard.RunnerTests',
  );
}
